# Generated by Django 3.1 on 2020-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favoriler',
            field=models.ManyToManyField(to='lessons.Baslik'),
        ),
        migrations.AddField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(to='lessons.Ders'),
        ),
    ]
