# Generated by Django 2.0 on 2019-08-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_adi', models.CharField(max_length=100, verbose_name='Üst Başlığın adı')),
                ('ana_başlık', models.CharField(choices=[('python', 'Python'), ('bootstrap4', 'Bootstrap4'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=30)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('modul_mu', models.BooleanField(default=False, verbose_name='Modül mü')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='Icon ismi')),
                ('sıra', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='baslık',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingilizce.Topic', verbose_name='Üst Başlık'),
            preserve_default=False,
        ),
    ]
