# Generated by Django 2.0 on 2019-08-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0002_auto_20190816_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='baslık',
        ),
    ]
