# Generated by Django 2.0 on 2019-08-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0003_remove_lesson_baslık'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='baslık',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingilizce.Topic', verbose_name='Üst Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='sıra',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
