# Generated by Django 2.0 on 2019-08-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0004_auto_20190816_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='baslık',
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=130),
        ),
    ]
