# Generated by Django 2.0 on 2019-08-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0005_auto_20190816_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='baslık',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingilizce.Topic', verbose_name='Üst Başlık'),
            preserve_default=False,
        ),
    ]
