# Generated by Django 2.0 on 2019-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0006_lesson_baslık'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
