# Generated by Django 2.0 on 2019-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0007_auto_20190817_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Aktif mi'),
        ),
        migrations.AddField(
            model_name='topic',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Aktif mi'),
        ),
    ]
