# Generated by Django 2.0 on 2019-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingilizce', '0008_auto_20190817_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='updating_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='güncelleme_tarihi'),
        ),
    ]
