# Generated by Django 2.0 on 2019-02-24 05:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma_tarihi')),
                ('filtre1', models.CharField(default='-', max_length=100)),
                ('filtre2', models.CharField(default='-', max_length=100)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
