# Generated by Django 2.0 on 2019-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='updating_date',
            field=models.DateTimeField(auto_now=True, verbose_name='yayımlanma_tarihi'),
        ),
    ]
