# Generated by Django 2.0 on 2019-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0002_dersler_updating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='anahtar',
            field=models.CharField(default='Python Dersleri', max_length=500),
        ),
        migrations.AddField(
            model_name='dersler',
            name='descriptions',
            field=models.CharField(default='Python Dersleri', max_length=500),
        ),
        migrations.AddField(
            model_name='dersler',
            name='slug2',
            field=models.SlugField(default='python', max_length=130),
        ),
    ]
