# Generated by Django 2.0 on 2019-08-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0003_auto_20190319_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baslik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_adi', models.CharField(max_length=100, verbose_name='Üst Başlığın adı')),
                ('ana_başlık', models.CharField(choices=[('python', 'Python'), ('bootstrap4', 'Bootstrap4'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=30)),
                ('slug', models.SlugField(max_length=130, unique=True)),
            ],
        ),
    ]
