# Generated by Django 2.0 on 2019-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0004_baslik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baslik',
            name='slug',
            field=models.SlugField(max_length=130),
        ),
    ]
