# Generated by Django 2.0 on 2019-08-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0005_auto_20190803_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='baslık',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tur.Baslik', verbose_name='Üst Başlık'),
            preserve_default=False,
        ),
    ]
