# Generated by Django 2.0 on 2019-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0008_baslik_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dersler',
            name='views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baslik',
            name='slug',
            field=models.SlugField(max_length=130, unique=True),
        ),
    ]
