# Generated by Django 2.0 on 2019-08-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0009_auto_20190807_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='baslik',
            name='sıra',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
