# Generated by Django 2.0 on 2019-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0010_baslik_sıra'),
    ]

    operations = [
        migrations.AddField(
            model_name='baslik',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Modül mü'),
        ),
        migrations.AddField(
            model_name='dersler',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Aktif mi'),
        ),
    ]
