# Generated by Django 2.0 on 2019-08-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0011_auto_20190817_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baslik',
            name='aktif',
            field=models.BooleanField(default=False, verbose_name='Aktif mi'),
        ),
        migrations.AlterField(
            model_name='baslik',
            name='ana_başlık',
            field=models.CharField(choices=[('python', 'Python'), ('bootstrap4', 'Bootstrap4'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')], default='python', max_length=30),
        ),
    ]
