# Generated by Django 2.0 on 2019-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0013_auto_20190907_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersler',
            name='updating_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='güncellenme_tarihi'),
        ),
    ]
