# Generated by Django 2.0 on 2019-06-22 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='resim')),
                ('kısa_içerik', ckeditor.fields.RichTextField()),
                ('uzun_içerik', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
