# Generated by Django 2.0 on 2019-06-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genel',
            options={'verbose_name': 'Genel-Konu', 'verbose_name_plural': 'Genel-Konular'},
        ),
    ]
