# Generated by Django 2.0 on 2019-08-18 13:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baslik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_adi', models.CharField(max_length=100, verbose_name='Üst Başlığın adı')),
                ('ana_başlık', models.CharField(choices=[('bootstrap4', 'Bootstrap4'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript')], default='python', max_length=30)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('modul_mu', models.BooleanField(default=False, verbose_name='Modül mü')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='Icon ismi')),
                ('sıra', models.PositiveSmallIntegerField(blank=True)),
                ('aktif', models.BooleanField(default=False, verbose_name='Aktif mi')),
            ],
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma_tarihi')),
                ('updating_date', models.DateTimeField(auto_now=True, verbose_name='yayımlanma_tarihi')),
                ('filtre1', models.CharField(default='-', max_length=100)),
                ('filtre2', models.CharField(default='-', max_length=100)),
                ('descriptions', models.CharField(default='Python Dersleri', max_length=500)),
                ('anahtar', models.CharField(default='Python Dersleri', max_length=500)),
                ('slug2', models.SlugField(default='python', max_length=130)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=False, verbose_name='Aktif mi')),
                ('baslık', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Baslik', verbose_name='Üst Başlık')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
