# Generated by Django 2.0 on 2019-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190618_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('ogrenci_sayisi',), 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='ogrenci_sayisi',
            field=models.PositiveIntegerField(default=0, verbose_name='öğrenci sayısı'),
        ),
    ]
