# Generated by Django 2.0 on 2019-05-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='isim',
            field=models.CharField(default='STUDENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='isim',
            field=models.CharField(default='TEACHER', max_length=30),
        ),
    ]
