# Generated by Django 2.0 on 2019-06-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinif',
            name='asistan',
            field=models.ManyToManyField(blank=True, related_name='asistanlar', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='hedef',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='isim',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='ogrenci',
            field=models.ManyToManyField(blank=True, related_name='ogrenciler', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='ogretmen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogretmenler', to='accounts.Teacher'),
        ),
    ]
