# Generated by Django 2.0 on 2019-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190610_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinif',
            name='hedef',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
