# Generated by Django 2.0 on 2019-06-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190613_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, choices=[('k', 'Kitap Okuma Turnuvası'), ('p', 'Kitap Okuma Etkinlikleri'), ('a', 'Anlamayı Geliştirme Turnuvası'), ('b', 'Birinci Sınıf Okuma Etkinliği'), ('o', 'Okul Öncesi Masal Etkinliği'), ('l', 'Lise "Kitap Koçum" Etkinliği')], max_length=1)),
                ('hedef', models.PositiveIntegerField(blank=True)),
                ('startting_date', models.DateTimeField(blank=True, max_length=30)),
                ('finishing_date', models.DateTimeField(blank=True, max_length=30)),
                ('ogretmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='etkinlikler',
            name='ogretmen',
        ),
        migrations.RemoveField(
            model_name='etkinlikler',
            name='sinif',
        ),
        migrations.RemoveField(
            model_name='sinif',
            name='okunan',
        ),
        migrations.DeleteModel(
            name='Etkinlikler',
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siniflar', to='accounts.Sinif'),
        ),
    ]
