# Generated by Django 2.0 on 2019-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190615_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='hedef',
            field=models.PositiveIntegerField(),
        ),
    ]
