# Generated by Django 2.0 on 2019-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190616_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlik',
            name='ogretmen',
        ),
        migrations.RemoveField(
            model_name='etkinlik',
            name='sinif',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='sinif',
            name='etkinlik',
            field=models.ManyToManyField(to='accounts.Etkinlik'),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='asistan',
            field=models.ManyToManyField(related_name='asistanlar', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='sinif',
            name='ogrenci',
            field=models.ManyToManyField(related_name='ogrenciler', to='accounts.Student'),
        ),
    ]
