# Generated by Django 2.0 on 2019-06-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190616_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinif',
            name='asistan',
        ),
        migrations.RemoveField(
            model_name='sinif',
            name='etkinlik',
        ),
        migrations.RemoveField(
            model_name='sinif',
            name='ogrenci',
        ),
        migrations.RemoveField(
            model_name='sinif',
            name='ogretmen',
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='asistan',
            field=models.ManyToManyField(related_name='asistanlar', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='ogrenci',
            field=models.ManyToManyField(related_name='ogrenciler', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='ogretmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogretmenler', to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='sinif_adi',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sinif',
        ),
    ]
