# Generated by Django 2.0 on 2019-03-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(verbose_name='Mesajınız')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma_tarihi')),
            ],
            options={
                'ordering': ['publishing_date'],
            },
        ),
    ]
