# Generated by Django 2.0 on 2019-09-03 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1)),
                ('user', models.ForeignKey(db_index=False, default=1, help_text='&lt;b&gt;akıllı olun&lt;/b&gt;', on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazar', to='denemeler.Author')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to='denemeler.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, choices=[('k', 'Kitap Okuma Turnuvası'), ('p', 'Kitap Okuma Etkinlikleri'), ('a', 'Anlamayı Geliştirme Turnuvası'), ('b', 'Birinci Sınıf Okuma Etkinliği'), ('o', 'Okul Öncesi Masal Etkinliği'), ('l', 'Lise "Kitap Koçum" Etkinliği')], max_length=1)),
                ('hedef', models.PositiveIntegerField(blank=True)),
                ('startting_date', models.DateTimeField(auto_now_add=True, max_length=30)),
                ('finishing_date', models.DateTimeField(auto_now=True, max_length=30)),
                ('odul', models.CharField(blank=True, choices=[('b', 'Birinci Ödül'), ('i', 'İkinci Ödül'), ('ü', 'Üçüncü Ödül'), ('d', 'Dördüncü Ödül')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=30)),
                ('sayfa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ondalıklı_sayı', models.DecimalField(decimal_places=2, default=585.56, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=30)),
                ('takim', models.CharField(blank=True, choices=[('t', 'Turuncu'), ('m', 'Mavi'), ('k', 'Kırmızı'), ('s', 'Sarı'), ('y', 'Yeşil')], max_length=1)),
                ('bireysel_odulu', models.CharField(blank=True, max_length=30)),
                ('takim_odulu', models.CharField(blank=True, max_length=30)),
                ('kitap', models.ManyToManyField(blank=True, related_name='kitaplar', to='denemeler.Kitap')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='denemeler.Teacher'),
        ),
        migrations.AddField(
            model_name='sinif',
            name='asistan',
            field=models.ManyToManyField(blank=True, related_name='asistanlar', to='denemeler.Student'),
        ),
        migrations.AddField(
            model_name='sinif',
            name='ogrenci',
            field=models.ManyToManyField(blank=True, related_name='ogrenciler', to='denemeler.Student'),
        ),
        migrations.AddField(
            model_name='sinif',
            name='ogretmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogretmenler', to='denemeler.Teacher'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='ogretmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denemeler.Teacher'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='sinif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siniflar', to='denemeler.Sinif'),
        ),
    ]
