# Generated by Django 2.0 on 2019-09-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='ondalıklı_sayı',
        ),
        migrations.AddField(
            model_name='model1',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
