# Generated by Django 2.0 on 2019-09-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0002_auto_20190903_1423'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='model1',
            order_with_respect_to='number',
        ),
    ]
