# Generated by Django 2.0 on 2019-09-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0003_auto_20190903_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model1',
            options={'ordering': ['number']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='model1',
            order_with_respect_to=None,
        ),
    ]
