# Generated by Django 2.0 on 2019-09-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0005_auto_20190903_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
                'default_permissions': (),
            },
        ),
    ]
