# Generated by Django 2.0 on 2019-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0006_model2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model2',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='model2',
            name='isim',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='model2',
            unique_together={('number', 'isim')},
        ),
        migrations.AddIndex(
            model_name='model2',
            index=models.Index(fields=['number', 'isim'], name='denemeler_m_number_56f732_idx'),
        ),
        migrations.AddIndex(
            model_name='model2',
            index=models.Index(fields=['isim'], name='isim_idx'),
        ),
    ]
