# Generated by Django 2.0 on 2019-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0007_auto_20190904_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model2',
            name='isim',
            field=models.CharField(max_length=50),
        ),
    ]
