# Generated by Django 2.0 on 2019-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0008_auto_20190904_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2m', models.ManyToManyField(related_name='denemeler_childa_related', related_query_name='denemeler_childas', to='denemeler.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2m', models.ManyToManyField(related_name='denemeler_childb_related', related_query_name='denemeler_childbs', to='denemeler.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
