# Generated by Django 2.0 on 2019-09-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denemeler', '0012_auto_20190911_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
