# Generated by Django 2.0 on 2020-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0002_auto_20200107_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baslik',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='ders',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
