# Generated by Django 2.0 on 2020-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0004_auto_20200110_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='baslik',
            name='favori_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=100, verbose_name='cevap'),
        ),
    ]
