# Generated by Django 2.0 on 2020-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersler', '0005_auto_20200112_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='baslik',
            name='begenilme_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
